server:
  port: 8092

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/calligraphy_platform?characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: Runkellen431
    driverClassName: com.mysql.cj.jdbc.Driver

mybatis:
  mapperLocations: classpath*:mapper/*.xml
  configuration:
    jdbc-type-for-null: 'null'
    lazy-loading-enabled: true
  type-aliases-package:
    com.calligraphy.domain.entity






